controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

publications:
    path: /publications
    controller: App\Controller\PostController::index


comment:
    path: /comment/{id}
    controller: App\Controller\PostController::addComment
