controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

publications:
    path: /publications
    controller: App\Controller\PostController::index


comment:
    path: /comment/{id}
    controller: App\Controller\PostController::addComment


api_controller:
    path: /api/users
    controller: App\Controller\ApiController::getUsers
    methods: [GET,POST,DELETE,UPDATE]


comment_confirm:
    path: '/comment/confirm/{id}'
    controller: 'App\Controller\PostController::confirmComment'

comment_infirm:
    path: '/comment/infirm/{id}'
    controller: 'App\Controller\PostController::infirmComment'
